PUT http://localhost:8080/cyclist/new
Content-Type: application/json

{ "name":  "ppyrka" }

> {% 
    client.global.set("cyclist_id", response.body.id);
%}

###

GET http://localhost:8080/cyclist/{{cyclist_id}}

###

GET http://localhost:8080/cyclist/{{cyclist_id}}/details

###

POST http://localhost:8080/cyclist/{{cyclist_id}}/addRoute
Content-Type: application/json

{
  "kilometers": 30.7,
  "startedAt": 1685951547232,
  "finishedAt": 1685957428000
}





### 

GET http://localhost:8080/cyclist/15391974-d47d-42bc-8eab-5786a9d31a48

###

GET http://localhost:8080/cyclist/15391974-d47d-42bc-8eab-5786a9d31a48/details

###

POST http://localhost:8080/cyclist/15391974-d47d-42bc-8eab-5786a9d31a48/addRoute
Content-Type: application/json

{
  "kilometers": 30.7,
  "startedAt": 1685951547232,
  "finishedAt": 1685957428000
}